Add support for projections on symbolic names
neo4j-contrib/cypher-dsl pull request #132
Opened 2021-02-09 12:15 UTC by Andy2003

resolves #131

2021-02-09 15:18 UTC, michael-simons requested changes
I do like the change for the actual issue, I am not a fan of broadening the API of the `RETURN`, `WITH` and other methods in the same PR.

2021-02-09 15:18 UTC, michael-simons commented on neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/SymbolicName.java
> +public class SymbolicName implements Expression, PropertyContainer {
That should not be necessary.

2021-02-09 16:24 UTC, Andy2003 commented
> I do like the change for the actual issue, I am not a fan of broadening the API of the `RETURN`, `WITH` and other methods in the same PR.

@michael-simons this was necessary otherwise there were conflicts b/c of the `PropertyContainer` which makes `SymbolicName` a `Named` and an `Expression`

So if I remove the `PropertyContainer` from `SymbolicName` I can revert all the other changes as well. 

Is that what you want?

2021-02-09 16:25 UTC, Andy2003 commented
> I do like the change for the actual issue, I am not a fan of broadening the API of the `RETURN`, `WITH` and other methods in the same PR.

@michael-simons this was necessary otherwise there were conflicts b/c of the `PropertyContainer` which makes `SymbolicName` a `Named` and an `Expression`

So if I remove the `PropertyContainer` from `SymbolicName` I can revert all the other changes as well. 

Is that what you want?

2021-02-09 16:25 UTC, Andy2003 commented
> I do like the change for the actual issue, I am not a fan of broadening the API of the `RETURN`, `WITH` and other methods in the same PR.

@michael-simons this was necessary otherwise there were conflicts b/c of the `PropertyContainer` which makes `SymbolicName` a `Named` and an `Expression`

So if I remove the `PropertyContainer` from `SymbolicName` I can revert all the other changes as well. 

Is that what you want?

2021-02-10 12:27 UTC, michael-simons commented
Closed in favor of 804dc246dcd364ce217ec1a2bd6350653c22490d

2021-02-10 12:27 UTC, closed without merging