Add support for path with node.
neo4j-contrib/cypher-dsl pull request #201
Opened 2021-06-25 08:12 UTC by meistermeier

According to https://s3.amazonaws.com/artifacts.opencypher.org/M15/railroad/PatternElement.html the `Node`(Pattern) is a valid type in parallel to the `RelationshipPattern` for path definitions.

Maybe this is too naive from my side but it seems to not break anything else or broadens the API too much when supporting this.

Closes #200

2021-06-26 14:58 UTC, michael-simons requested changes
Both `Node` and `RelationshipPattern` are `PatternElement`'s as defined by OpenCypher. Please change it to the `PatternElement` and drop the superflous method again. Thanks :)

2021-06-28 06:41 UTC, meistermeier commented
But this would also mean that a `NamedPath` will get accepted and lead to wrong Cypher :crying_cat_face:

2021-06-28 09:09 UTC, michael-simons commented
Shoot. We could either extract than the optional pattern if available or throw an exception.
I prefer either of those than breading the api here, with a slight tendency to just extract the optional pattern and only throw when there is none.

2021-06-28 13:07 UTC, meistermeier commented
Still struggling with myself about those two lines https://github.com/neo4j-contrib/cypher-dsl/pull/201/commits/9a59961c7d6a88040691ed63333e61e63abd12fa#diff-9ca0525da9abc98ae49a814065773de938ad2c0b29a70b4129a55e5863404b5aR133
Because if we ninja like sneak the previous existing pattern, we would need to have also the old `SymbolicName`. Otherwise the references will be broken/mixed up, IMHO.

2021-06-28 14:07 UTC, michael-simons commented
other solution would be just returning the existing named path… probably a lot less error prone

2021-06-28 14:23 UTC, meistermeier commented
Thought the same. Because (for good reasons) there is no logging, I would provide this information JavaDoc-wise.

2021-06-29 08:50 UTC, michael-simons approved these changes

2021-06-29 08:52 UTC, merged